name: Update Pure
on:
  workflow_dispatch:
  schedule:
    # at 21:00 on every Saturday (UTC) = at 6:00 on every Sunday (JST)
    - cron: "0 21 * * SAT"
jobs:
  update-pure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update Pure
        run: |
          set -x
          CURRENT_VERSION=$(cat pure-version)
          LATEST_VERSION=$(
            curl -s "https://api.github.com/repos/sindresorhus/pure/releases/latest" | \
            jq -r .tag_name
          )
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "$LATEST_VERSION" >pure-version
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            BRANCH="update-pure-${{ github.run_number }}"
            git checkout -b "$BRANCH"
            git add pure-version
            git commit -m "Update Pure to ${LATEST_VERSION}"
            git push origin "$BRANCH"
            gh pr create --base main --head "$BRANCH" --title "Update Pure to ${LATEST_VERSION}" --body ""
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
